### ISSUE TITLE
homebrew throws an error when downloading 1.4.0: curl: (22) The requested URL returned error: 526

### ISSUE THREAD

**Issue by alexhaas** [go-gitea/homebrew-gitea#34]
1.4.0 isn't being offered from brew.

**Comment by alexhaas** [comment]
yeah it is... idk how to use brew apparently...

**Comment by alexhaas** [comment]
==> Upgrading go-gitea/gitea/gitea 
==> Downloading https://dl.gitea.io/gitea/1.4.0/gitea-1.4.0-darwin-10.6-amd64

curl: (22) The requested URL returned error: 526 
Error: Failed to download resource "gitea"
Download failed: https://dl.gitea.io/gitea/1.4.0/gitea-1.4.0-darwin-10.6-amd64

**Comment by lunny** [comment]
Because dl.gitea.io is broken currently after we upgraded the DO plan.

**Comment by lafriks** [comment]
Should be fixed
